<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.4/css/all.css">
<link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="node_modules/noty/lib/noty.css">
<link rel="stylesheet" href="node_modules/noty/lib/themes/sunset.css">
<link rel="stylesheet" href="node_modules/sweetalert2/dist/sweetalert2.min.css">
<link rel="stylesheet" href="node_modules/icheck-bootstrap/icheck-bootstrap.min.css">
<link rel="stylesheet" href="node_modules/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css">
<link rel="stylesheet" href="plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
<link rel="stylesheet" href="plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
<link rel="stylesheet" href="plugins/datatables-select/css/select.bootstrap4.min.css">
<link rel="stylesheet" href="plugins/bs-stepper/css/bs-stepper.min.css">
<link rel="stylesheet" href="plugins/rescalendar/rescalendar.css">
<link rel="stylesheet" href="node_modules/perfect-scrollbar/css/perfect-scrollbar.css">
<link rel="stylesheet" href="dist/css/adminlte.css">
<link rel="stylesheet" href="dist/css/system.min.css">